### ISSUE TITLE
How to build the App

### ISSUE THREAD

**Issue by rozularen** [dsyer/spring-boot-angular#8]
Hi, first of all thanks for the detailed guide!

I am tring to build the app after following the instructions, but it seems there are many different ways to build it.

I can build the whole app (front + back) like this:
**$ ./mvnw spring-boot:run** 
And I'd have it running at **localhost:8080**. To see the generated UUID and the greeting message I have to move to **localhost:8080/resource** 

I can also build only the front like this:
**$ ./npm start**
or
**$ ./ng serve**
or
**$ ./ng build # optionally with --watch**
And I'd get the front running at **localhost:4200**
I don't understand why when loading **localhost:4200** I get a different page with the Angular logo and some links to the Angular documentation and Angular blog.
If I run the app with ./mvnw spring-boot:run I can only see a JSON with the ID and the greeting message when loading localhost:8080/resource without any index.html or anything like that.

I suppose I have to always build the app with the mvn command but I am confused about wheter I am doing it wrong because I'm not seeing neither the ID or the greeting message when executing ./ng build 

I'm plannign to have the SPA hosted at www.example.com and the Spring backend API at something like www.example.com/api so the front and the back are in the same domain but different directories but somehow I think I am doing something wrong or it just can't be like that, any tips are welcome!!

Thanks!

**Comment by MuhammedOzdogan** [comment]
I have same problem. Unfortunately in spring official tutorial again same problem: https://spring.io/guides/tutorials/spring-security-and-angular-js/

I think only way to work Angular and Spring boot in same host is  
developing Spring boot Rest Services and Angular separate folders.
After development process using "ng build" for angular project and copying content of "dist/project-name" into to spring boot app "src/main/resources/static" folder. Because by the time spring boot is up, it is look for index.html in "src/main/resources/static"

But I am not sure is this the correct way to develop Single Page Web Application with Spring Boot. 

![capture](https://user-images.githubusercontent.com/26257939/40659341-a876885a-6356-11e8-832f-fe33e40c5392.PNG)

**Comment by rozularen** [comment]
Hey Muhammed, thanks for sharing!

Right now I am at work so I can't get much into details but when I was working on this side project serving an Angular app from a Spring boot backend, I came up with this article:

http://www.devglan.com/spring-boot/spring-boot-angular-deployment

It looked decent to me but I still don't know what are the preferred method to deploy an Angular app.

Cheers, Marcos.

**Comment by MuhammedOzdogan** [comment]
Thanks Marcos, 

I found this https://blog.jdriven.com/2016/12/angular2-spring-boot-getting-started/
This is building a spring boot app with angular from starch in the same host :)
But this situation with Spring official tutorial has sad me.

**Comment by dsyer** [comment]
The app in this project works if you build and run it from Maven or the IDE (I used VSCode), as long as you have all the right features installed. The idea was to have a single app, not a front end and a back end (which is not what you need in production), so running `./ng serve` is never going to work.
